version: "3"

networks:
  backend:

volumes:
  db-data:

services:
  checker-server:
    image: d1ablorus/checker-server
    container_name: checker-server
    environment:
      - VIRTUAL_HOST=checker.d1ablo.ru
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=checker.d1ablo.ru
      - LETSENCRYPT_EMAIL=admin@d1ablo.ru
      - POSTGRES_HOST=checker-db
    depends_on:
      - nginx-proxy
      - letsencrypt-nginx
      - checker-db
    restart: unless-stopped
    networks:
      - frontend
      - backend
    logging:
      options:
        max-file: '3'
        max-size: 10m

  checker-db:
    image: postgres:alpine
    container_name: checker-db
    environment:
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    logging:
      options:
        max-file: '3'
        max-size: 10m
