version: "3"

networks:
  masscan-net:
    driver: bridge

volumes:
  store:

services:
  masscan:
    image: d1ablorus/masscan
    container_name: masscan
    volumes:
      - store:/opt
    restart: unless-stopped
    networks:
      - masscan-net
    logging:
      options:
        max-file: '3'
        max-size: 10m
    environment:
      - PORTS=8080,3128,3129
      - SHARDS=1/3
    depends_on:
      - masscan-check
  masscan-check:
    image: d1ablorus/masscan
    container_name: masscan-check
    volumes:
      - store:/opt
    restart: unless-stopped
    networks:
      - masscan-net
    logging:
      options:
        max-file: '3'
        max-size: 10m
    command:
      - proxy_check.sh
