version: "3"

networks:
  frontend:
    external: true
  backend:

volumes:
  db-data:

services:
  proxycheck-server:
    image: d1ablorus/proxycheck-server
    container_name: proxycheck-server
    environment:
      - VIRTUAL_HOST=proxy.d1ablo.ru
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=proxy.d1ablo.ru
      - LETSENCRYPT_EMAIL=admin@d1ablo.ru
      - POSTGRES_HOST=proxycheck-db
    depends_on:
      - nginx-proxy
      - letsencrypt-nginx
      - proxycheck-db
    restart: unless-stopped
    networks:
      - frontend
      - backend
    logging:
      options:
        max-file: '3'
        max-size: 10m

  proxycheck-db:
    image: postgres:alpine
    container_name: proxycheck-db
    environment:
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    logging:
      options:
        max-file: '3'
        max-size: 10m
