version: "3"

networks:
  proxy:

volumes:
  proxy:

services:
  proxycheck-client:
    image: d1ablorus/proxycheck-client
    container_name: proxycheck-client
    volumes:
      - proxy:/opt
    restart: unless-stopped
    networks:
      - proxy
    environment: &environment
      - JOBS=150
      - TREADS=150
      - SITE=https://vk.com
      - PROXYLIST=/opt/proxylist.txt
      - APIURL=https://proxy.d1ablo.ru
    logging:
      options:
        max-file: '3'
        max-size: 10m
  proxylists:
    image: d1ablorus/proxylists
    container_name: proxylists
    volumes:
      - proxy:/opt
    depends_on:
      - proxycheck-client
    restart: unless-stopped
    networks:
      - proxy
    environment: *environment
    logging:
      options:
        max-file: '3'
        max-size: 10m
  pyproxyhunter:
    image: d1ablorus/pyproxyhunter
    container_name: pyproxyhunter
    volumes:
      - proxy:/opt
    depends_on:
      - proxycheck-client
    restart: unless-stopped
    networks:
      - proxy
    environment: *environment
    logging:
      options:
        max-file: '3'
        max-size: 10m
  proxybroker:
    image: d1ablorus/proxybroker
    container_name: proxybroker
    volumes:
      - proxy:/opt
    depends_on:
      - proxycheck-client
    restart: unless-stopped
    networks:
      - proxy
    environment: *environment
    logging:
      options:
        max-file: '3'
        max-size: 10m
